# Form implementation generated from reading ui file 'encrypt.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem, QTableWidget
from qt_material import apply_stylesheet
import codecs
from gammaCoder import GammaCoder


class Ui_MainWindow(object):

    KEYWORD = "ракокраб"

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lbInitial = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbInitial.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.lbInitial.setObjectName("lbInitial")

        self.teInitial = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.teInitial.setGeometry(QtCore.QRect(10, 30, 771, 251))
        self.teInitial.setObjectName("teInitial")
        self.teInitial.setReadOnly(True)

        self.lbEncrypted = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbEncrypted.setGeometry(QtCore.QRect(10, 290, 161, 16))
        self.lbEncrypted.setObjectName("lbEncrypted")

        self.teEncrypted = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.teEncrypted.setGeometry(QtCore.QRect(10, 310, 501, 251))
        self.teEncrypted.setObjectName("teEncrypted")
        self.teEncrypted.setReadOnly(True)

        # self.imgTab = QtGui.QPixmap("table.png")

        # self.imgTable = QtWidgets.QGraphicsView(parent=self.centralwidget)
        # self.imgTable.setGeometry(QtCore.QRect(530, 30, 251, 251))
        # self.imgTable.setObjectName("imgTable")

        # self.lbTable = QtWidgets.QLabel(parent=self.centralwidget)
        # self.lbTable.setGeometry(QtCore.QRect(530, 10, 101, 16))
        # self.lbTable.setObjectName("lbTable")
        # self.lbTable.setPixmap(self.imgTab)

        self.btnOpen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(530, 450, 251, 41))
        self.btnOpen.setObjectName("btnOpen")
        self.btnOpen.clicked.connect(self.openFile)

        self.btnEncrypt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(530, 520, 141, 41))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnEncrypt.clicked.connect(self.encrypt)

        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(680, 520, 101, 41))
        self.btnExit.setObjectName("btnExit")
        self.btnExit.clicked.connect(self.exit)

        self.lbKeyword = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbKeyword.setGeometry(QtCore.QRect(530, 310, 101, 16))
        self.lbKeyword.setObjectName("lbKeyword")

        self.leKeyword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leKeyword.setGeometry(QtCore.QRect(530, 330, 251, 21))
        self.leKeyword.setObjectName("leKeyword")
        self.leKeyword.setText(self.KEYWORD)

        # self.table = QTableWidget(parent=self.centralwidget)  # Create a table
        # self.table.setGeometry(QtCore.QRect(530, 30, 681, 251))
        # self.table.setColumnCount(6)  # Set three columns
        # self.table.setRowCount(6)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        import os
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rakocrab Software"))
        MainWindow.setWindowIcon(QtGui.QIcon(os.path.dirname(__file__) + "/rakocrab.png"))
        self.lbInitial.setText(_translate("MainWindow", "Текст файла"))
        self.lbEncrypted.setText(_translate("MainWindow", "Зашифрованный текст"))
        # self.lbTable.setText(_translate("MainWindow", "Таблица замен"))
        self.btnOpen.setText(_translate("MainWindow", "Открыть файл"))
        self.btnEncrypt.setText(_translate("MainWindow", "Зашифровать"))
        self.btnExit.setText(_translate("MainWindow", "Выход"))
        self.lbKeyword.setText(_translate("MainWindow", "Ключевое слово"))

    
    def openFile(self):
        filename, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open File", "", "All Files(*);;Text Files(*.txt)")
        if filename:
            with codecs.open(filename, 'r', "utf-8") as file:
                text = file.read()
                file.close()
                self.teInitial.setText(text)


    def encrypt(self):
        import os
        alphabet = "абвгдежзийклмнопрстуфхцчшщъыьэюя "
        coder = GammaCoder()
        message = self.teInitial.toPlainText().strip().lower()
        keyword = self.leKeyword.text().lower()

        encryptedText = coder.encrypt(alphabet, message, keyword)

        with codecs.open(os.path.dirname(__file__) + "/encrypted.txt", 'w', "utf-8") as file:
            file.write(encryptedText)
            self.teEncrypted.setText(encryptedText)


    def exit(self):
        MainWindow.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    apply_stylesheet(app, theme='dark_blue.xml')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
